# Generated by Django 4.2.1 on 2023-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='init_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1, max_digits=9, null=True),
        ),
    ]
