# Generated by Django 4.2.1 on 2023-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_currency_alter_post_init_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='init_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
