# Generated by Django 4.2.1 on 2023-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
